export const mockIssues = [
  {
    id: 1001,
    number: 101,
    title: "Improve README documentation for installation",
    description: "Clarify installation steps and add a small troubleshooting section for new contributors.",
    repository: "open-source-labs/python-toolkit",
    repositoryUrl: "https://github.com/open-source-labs/python-toolkit",
    issueUrl: "https://github.com/open-source-labs/python-toolkit/issues/101",
    language: "Python",
    topics: ["python", "developer-tools", "documentation"],
    labels: ["good first issue", "documentation"],
    stars: 820,
    contributors: 28,
    updatedAt: "2026-09-25T10:30:00Z",
    createdAt: "2026-08-25T10:30:00Z",
    comments: 2,
    difficulty: "Beginner",
    difficultyScore: 1,
    difficultyReasons: ["Good first issue label", "Documentation task", "Low comment count"],
    skills: ["Python", "Markdown", "Git"],
    score: 94
  },
  {
    id: 1002,
    number: 42,
    title: "Add example for model evaluation",
    description: "Add a small example showing how users can evaluate a trained model.",
    repository: "community/ml-starter",
    repositoryUrl: "https://github.com/community/ml-starter",
    issueUrl: "https://github.com/community/ml-starter/issues/42",
    language: "Python",
    topics: ["machine-learning", "python", "tutorial"],
    labels: ["help wanted", "beginner"],
    stars: 1460,
    contributors: 41,
    updatedAt: "2026-09-23T12:00:00Z",
    createdAt: "2026-08-01T12:00:00Z",
    comments: 5,
    difficulty: "Easy",
    difficultyScore: 2,
    difficultyReasons: ["Beginner label", "Help wanted label", "Low comment count"],
    skills: ["Python", "Machine Learning"],
    score: 90
  },
  {
    id: 1003,
    number: 77,
    title: "Fix validation message in signup form",
    description: "Update the client-side validation message and add a small test case.",
    repository: "beginner-web/react-dashboard",
    repositoryUrl: "https://github.com/beginner-web/react-dashboard",
    issueUrl: "https://github.com/beginner-web/react-dashboard/issues/77",
    language: "JavaScript",
    topics: ["react", "javascript", "frontend"],
    labels: ["good first issue", "bug"],
    stars: 2340,
    contributors: 65,
    updatedAt: "2026-09-24T08:15:00Z",
    createdAt: "2026-08-20T08:15:00Z",
    comments: 7,
    difficulty: "Beginner",
    difficultyScore: 1,
    difficultyReasons: ["Good first issue label", "Small bug-fix signal", "Low comment count"],
    skills: ["JavaScript", "React", "Testing"],
    score: 88
  },
  {
    id: 1004,
    number: 13,
    title: "Add unit tests for date utility",
    description: "Add tests for edge cases around date formatting and timezone conversion.",
    repository: "oss-utils/js-toolbox",
    repositoryUrl: "https://github.com/oss-utils/js-toolbox",
    issueUrl: "https://github.com/oss-utils/js-toolbox/issues/13",
    language: "TypeScript",
    topics: ["typescript", "testing", "utilities"],
    labels: ["good first issue", "testing"],
    stars: 510,
    contributors: 19,
    updatedAt: "2026-09-18T14:10:00Z",
    createdAt: "2026-07-18T14:10:00Z",
    comments: 9,
    difficulty: "Easy",
    difficultyScore: 2,
    difficultyReasons: ["Good first issue label", "Testing task", "Moderate comment count"],
    skills: ["TypeScript", "Testing", "Git"],
    score: 83
  }
];
